// src/app/core/permissions/permission.types.ts

export enum Permission {
  VIEW_TRANSACTIONS = 'VIEW_TRANSACTIONS',
  MANAGE_TRANSACTIONS = 'MANAGE_TRANSACTIONS',
  VIEW_BUDGETS = 'VIEW_BUDGETS',
  MANAGE_BUDGETS = 'MANAGE_BUDGETS',
  VIEW_REPORTS = 'VIEW_REPORTS',
  MANAGE_ACCOUNT = 'MANAGE_ACCOUNT',
  MANAGE_USERS = 'MANAGE_USERS',
  VIEW_ANALYTICS = 'VIEW_ANALYTICS',
}
